<#
Orchestration script to build solution, docker image and run integration tests.
This script is intended to live in the `src/` folder next to `Asionyx.sln`.
Usage: pwsh ./build-test-and-deploy.ps1
#>
param()


# Note: static appsettings.json files are checked into each project folder so the
# runtime does not require appsettings to be generated by this script.

function New-Directory {
    [CmdletBinding(DefaultParameterSetName = 'Default')]
    param(
        [Parameter(Mandatory = $true, Position = 0)]
        [string] $Path
    )
    if (-not (Test-Path $Path)) { New-Item -ItemType Directory -Path $Path | Out-Null }
}

function Restore-Solution {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        $buildContext
    )

    # local variables used in this function
    $solution = 'Asionyx.sln'

    Write-Host "Restoring solution: $solution" -ForegroundColor Green
    dotnet restore $solution
    if ($LASTEXITCODE -ne 0) { Write-Host "dotnet restore failed" -ForegroundColor Red; exit $LASTEXITCODE }

    Write-Host "Building solution: $solution" -ForegroundColor Green
    dotnet build $solution -c Release
    if ($LASTEXITCODE -ne 0) { Write-Host "dotnet build failed" -ForegroundColor Red; exit $LASTEXITCODE }
}

function Publish-Projects {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        $buildContext
    )

    # locals
    $publishRoot = $buildContext.PublishRoot
    Write-Host "Publishing projects to $publishRoot..." -ForegroundColor Green
    if (Test-Path $publishRoot) { Remove-Item $publishRoot -Recurse -Force }

    $projects = @(
        @{ Name = 'Asionyx.Services.Deployment'; Out = 'deployment'; Args = '' },
        @{ Name = 'Asionyx.Services.Deployment.SystemD'; Out = 'systemd'; Args = '-r linux-x64 -p:PublishSingleFile=true -p:PublishTrimmed=false -p:SelfContained=true' },
        @{ Name = 'Asionyx.Services.HelloWorld'; Out = 'helloworld'; Args = '' }
    )

    $projects | % {
        $outDir = Join-Path $publishRoot $_.Out
        New-Directory -Path $outDir
        Write-Host "Publishing $($_.Name) -> $outDir" -ForegroundColor Green
        if ([string]::IsNullOrWhiteSpace($_.Args)) {
            dotnet publish $_.Name -c Release -o $outDir
        } else {
            $extraArgs = $_.Args -split ' '
            $argList = @('publish', $_.Name, '-c', 'Release') + $extraArgs + @('-o', $outDir)
            & dotnet @argList
        }
        if ($LASTEXITCODE -ne 0) { Write-Host "dotnet publish $($_.Name) failed" -ForegroundColor Red; exit $LASTEXITCODE }
    }
}

function Invoke-DockerBuild {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        $buildContext
    )

    # locals
    $dockerfile = $buildContext.Dockerfile
    $dockerImage = $buildContext.DockerImage

    Write-Host "Building docker image $dockerImage (linux)" -ForegroundColor Green
    docker build -f $dockerfile -t $dockerImage .
}

function Remove-DockerImage {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        $buildContext
    )

    $dockerImage = $buildContext.DockerImage
    Write-Host "Removing docker image $dockerImage (if present)" -ForegroundColor Green
    try {
        docker rmi -f $dockerImage | Out-Null
    } catch {
        Write-Host "docker image removal failed or image not present: $_" -ForegroundColor Yellow
    }
}

# Container lifecycle is managed by integration tests (Testcontainers). The orchestrator
# should only build/publish and build the Docker image; it must NOT start or remove containers.

function Test-Integration {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        $buildContext
    )

    Write-Host "Running integration tests" -ForegroundColor Green
    # Run integration test project (contains all Docker-backed integration tests)
    dotnet test Asionyx.Services.Deployment.IntegrationTests -c Release --no-build
    # Run unit/in-memory tests
    dotnet test Asionyx.Services.Deployment.Tests -c Release --no-build
}

function Save-LogsAndCleanup {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        $buildContext
    )

    $scriptDir = $buildContext.ScriptDir
    $diagBase = Join-Path $scriptDir 'artifacts'
    if (-not (Test-Path $diagBase)) { New-Item -ItemType Directory -Path $diagBase | Out-Null }
    $diagHost = Join-Path $diagBase ("diagnostics_{0}" -f (Get-Date -Format 'yyyyMMddHHmmss'))
    if (-not (Test-Path $diagHost)) { New-Item -ItemType Directory -Path $diagHost | Out-Null }

    # We do not start containers here; integration tests start/stop containers themselves.
    # Only perform local cleanup of publish artifacts and leave docker images/containers alone.
    try {
        if (Test-Path $buildContext.PublishRoot) {
            Write-Host "Cleaning up publish folder $($buildContext.PublishRoot)" -ForegroundColor Green
            Remove-Item $buildContext.PublishRoot -Recurse -Force
        }
        Write-Host "Orchestration complete (image built; container lifecycle is test-managed)." -ForegroundColor Green
    } catch {
        Write-Host "Cleanup failed: $_" -ForegroundColor Yellow
        exit 0
    }
}

$ErrorActionPreference = 'Stop'
$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
Set-Location $scriptDir

# Centralized configuration (edit here)
$PublishRoot = Join-Path $scriptDir 'publish'
$DeploymentProjectPath = Join-Path $scriptDir 'Asionyx.Services.Deployment'
$SystemdProjectPath = Join-Path $scriptDir 'Asionyx.Services.Deployment.SystemD'
$HelloWorldProjectPath = Join-Path $scriptDir 'Asionyx.Services.HelloWorld'
$Dockerfile = 'Asionyx.Services.Deployment.Docker/Dockerfile'
$DockerImage = 'asionyx/deployment:local'
$ContainerName = 'asionyx_local'
$HostPort = 5000
$MaxWaitSeconds = 60
$DiagnosticsToStdout = $true
$DiagnosticsDir = '/var/asionyx/diagnostics'
$InsecureTesting = $true


# Build context object passed to every function
$buildContext = [PSCustomObject]@{
    ScriptDir = $scriptDir
    PublishRoot = $PublishRoot
    DeploymentProjectPath = $DeploymentProjectPath
    SystemdProjectPath = $SystemdProjectPath
    HelloWorldProjectPath = $HelloWorldProjectPath
    Dockerfile = $Dockerfile
    DockerImage = $DockerImage
    ContainerName = $ContainerName
    HostPort = $HostPort
    MaxWaitSeconds = $MaxWaitSeconds
    DiagnosticsToStdout = $DiagnosticsToStdout
    DiagnosticsDir = $DiagnosticsDir
    InsecureTesting = $InsecureTesting
}

Restore-Solution -buildContext $buildContext
Publish-Projects -buildContext $buildContext
Invoke-DockerBuild -buildContext $buildContext

# Run integration tests but always remove the built image afterwards. Container
# lifecycle remains managed by the tests themselves.
try {
    Test-Integration -buildContext $buildContext
} finally {
    Remove-DockerImage -buildContext $buildContext
    Save-LogsAndCleanup -buildContext $buildContext
}